# Generated by Django 5.2.9 on 2026-01-22 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("323b0617-0135-4691-9490-44cdeec9f41d"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("log_date", models.DateField()),
                (
                    "log_type",
                    models.CharField(
                        choices=[("ORIGINAL", "Original"), ("DUPLICATE", "Duplicate")],
                        default="ORIGINAL",
                        max_length=20,
                    ),
                ),
                ("from_location", models.CharField(blank=True, max_length=255)),
                ("to_location", models.CharField(blank=True, max_length=255)),
                (
                    "total_miles_driving_today",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_mileage_today",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("truck_tractor_number", models.CharField(blank=True, max_length=100)),
                (
                    "trailer_numbers",
                    models.JSONField(default=list, help_text="List of trailer numbers"),
                ),
                ("license_plate", models.CharField(blank=True, max_length=50)),
                ("license_state", models.CharField(blank=True, max_length=2)),
                ("carrier_name", models.CharField(blank=True, max_length=255)),
                ("main_office_address", models.TextField(blank=True)),
                ("home_terminal_address", models.TextField(blank=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "recap_data",
                    models.JSONField(
                        default=dict, help_text="Daily recap calculations"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShippingDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("323b0617-0135-4691-9490-44cdeec9f41d"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bill_of_lading_number", models.CharField(max_length=100)),
                ("shipper_name", models.CharField(blank=True, max_length=255)),
                ("commodity", models.CharField(blank=True, max_length=255)),
                (
                    "daily_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_documents",
                        to="driver_hos_logbook.dailylog",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("323b0617-0135-4691-9490-44cdeec9f41d"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_location", models.CharField(max_length=255)),
                (
                    "current_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "current_lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("pickup_location", models.CharField(max_length=255)),
                (
                    "pickup_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "pickup_lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("dropoff_location", models.CharField(max_length=255)),
                (
                    "dropoff_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "dropoff_lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "current_cycle_used",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hours used in the current 70-hour/8-day cycle",
                        max_digits=5,
                    ),
                ),
                (
                    "total_distance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total calculated distance in miles",
                        max_digits=10,
                    ),
                ),
                (
                    "route_geometry",
                    models.JSONField(
                        blank=True,
                        help_text="OSRM route geometry coordinates",
                        null=True,
                    ),
                ),
                (
                    "daily_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="driver_hos_logbook.dailylog",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("323b0617-0135-4691-9490-44cdeec9f41d"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("PICKUP", "Pickup"),
                            ("DROPOFF", "Dropoff"),
                            ("FUEL", "Fueling"),
                            ("BREAK", "30-Minute Break"),
                            ("REST", "10-Hour Rest"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("arrival_time", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="driver_hos_logbook.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["arrival_time"],
            },
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("323b0617-0135-4691-9490-44cdeec9f41d"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "duty_status",
                    models.CharField(
                        choices=[
                            ("OFF_DUTY", "Off Duty"),
                            ("SLEEPER_BERTH", "Sleeper Berth"),
                            ("DRIVING", "Driving"),
                            ("ON_DUTY_NOT_DRIVING", "On Duty (Not Driving)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("location", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="driver_hos_logbook.trip",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Log entries",
                "ordering": ["start_time"],
            },
        ),
    ]
